/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/argos"
#define HOST_X86_64 1
#define HOST_LONG_BITS 64
#define HAVE_BYTESWAP_H 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define CONFIG_OSS 1
#define QEMU_VERSION "0.9.1"
#define ARGOS_VERSION "0.4.2-1"
#define CONFIG_SDL 1
#define ARGOS_NET_TRACKER
#define CONFIG_UNAME_RELEASE ""
