#ifndef _WINXP_INTERNALS_H
#define _WINXP_INTERNALS_H

#define IMAGE_DOS_SIGNATURE 0x5A4D
#define IMAGE_PE_SIGNATURE 0x00004550

// Offsets into the struct _TEB
#define TEB_CLIENT_ID 0x20
#define TEB_PROCESS_ENVIRONMENT_BLOCK 0x30
// Offsets into the struct _PEB
#define PEB_LOADER_DATA 0xc
// Offsets into the struct _PEB_LDR_DATA
#define PEB_LDR_DATA_INITIALIZED 0x4
#define PEB_LDR_DATA_IN_LOAD_ORDER_MODULE_LIST 0xc
// Offsets into the struct _LDR_MODULE
#define LDR_MODULE_BASE_ADDRESS 0x18
#define LDR_MODULE_BASE_DLL_NAME 0x2c
// Offsets into the struct UNICODE_STRING
#define UNICODE_STRING_LENGTH 0x0
#define UNICODE_STRING_MAXIMUM_LENGTH 0x2
#define UNICODE_STRING_BUFFER 0x4
// Offsets into the struct LIST_ENTRY
#define LIST_ENTRY_FLINK 0x0
#define LIST_ENTRY_BLINK 0x4
// Offsets into the struct CLIENT_ID
#define CLIENT_ID_UNIQUE_PROCESS 0x0
#define CLIENT_ID_UNIQUE_THREAD 0x4
// Offsets into the struct IMAGE_DOS_HEADER
#define IMAGE_DOS_HEADER_E_MAGIC 0x0
#define IMAGE_DOS_HEADER_E_LFANEW 0x3c
// Offsets into the struct IMAGE_NT_HEADERS
#define IMAGE_NT_HEADERS_SIGNATURE 0x0
#define IMAGE_NT_HEADERS_FILE_HEADER 0x4
#define IMAGE_NT_HEADERS_OPTIONAL_HEADER 0x18
// Offsets into the struct IMAGE_OPTIONAL_HEADER
#define IMAGE_OPTIONAL_HEADER_SIZE_OF_IMAGE 0x38
#define IMAGE_OPTIONAL_HEADER_NUMBER_OF_RVA_AND_SIZES 0x5c
#define IMAGE_OPTIONAL_HEADER_DATA_DIRECTORY 0x60
// Offsets into the struct IMAGE_DATA_DIRECTORY
#define IMAGE_DATA_DIRECTORY_VIRTUAL_ADDRESS 0x0
#define IMAGE_DATA_DIRECTORY_SIZE 0x4
// Offsets into the struct IMAGE_EXPORT_DIRECTORY
#define IMAGE_EXPORT_DIRECTORY_NAME 0xc
#define IMAGE_EXPORT_DIRECTORY_BASE 0x10
#define IMAGE_EXPORT_DIRECTORY_NUMBER_OF_FUNCTIONS 0x14
#define IMAGE_EXPORT_DIRECTORY_NUMBER_OF_NAMES 0x18
#define IMAGE_EXPORT_DIRECTORY_ADDRESS_OF_FUNCTIONS 0x1c
#define IMAGE_EXPORT_DIRECTORY_ADDRESS_OF_NAMES 0x20
#define IMAGE_EXPORT_DIRECTORY_ADDRESS_OF_NAME_ORDINALS 0x24
#endif
